# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 767d47334f78d8e610fc4eb6786b68366cf7042ab69837417301622560b3bf5aac0a803d0dc6756e709181067307d9b3a8f64d58075274b30b4a620258b1cc98

test:
  secret_key_base: 398416b3d4cf965935e380b595331c2d7bcdad4e4603ec9b1f79362b6eff3a8202ce020c927a4971942b5fe5b9599f3e219d4bfae02e642916d76dc392900eff

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
